export const essentialOils = [
  { name: "完全依蘭", components: "倍半萜烯、酯類", physical: "催情放鬆、平衡油脂", emotional: "鼓舞情緒、解除焦慮", meridians: "心經、腎經、心包經" },
  { name: "真正薰衣草", components: "酯類、單萜醇", physical: "抗菌、抗炎、改善睡眠", emotional: "放鬆心情、減輕焦慮", meridians: "心經、肝經、肺經、三焦經" },
  { name: "茶樹", components: "單萜醇 (萜品烯-4-醇)", physical: "抗菌、抗病毒、治療痘痘", emotional: "幫助呼吸順暢、淨化思緒", meridians: "肺經、大腸經" },
  { name: "澳洲尤加利", components: "氧化物 (1,8-桉油醇)", physical: "淨化呼吸道、舒緩感冒", emotional: "提振精神、澄清思緒", meridians: "肺經、大腸經" },
  { name: "穗花薰衣草", components: "氧化物、單萜酮", physical: "舒緩肌肉痠痛、抗菌", emotional: "提振精神、減輕疲勞", meridians: "肺經、肝經" },
  { name: "百里酚百里香", components: "單萜酚 (百里酚)", physical: "強效抗菌、抗感染", emotional: "提振精神、增強意志力", meridians: "肺經、腎經" },
  { name: "野生百里香", components: "單萜酚 (香芹酚、百里酚)", physical: "抗菌、促進免疫", emotional: "激勵情緒、消除疲勞", meridians: "肺經、腎經" },
  { name: "薑CO2", components: "倍半萜烯 (薑烯)", physical: "舒緩暈車噁心、溫暖四肢", emotional: "提振精神、消除疲憊", meridians: "脾經、胃經、腎經" },
  { name: "岩蘭草", components: "倍半萜醇、倍半萜酮", physical: "深度放鬆、紮根大地", emotional: "得到安全感、安撫負面情緒", meridians: "脾經、胃經、腎經、三焦經" },
  { name: "廣藿香", components: "倍半萜醇 (廣藿香醇)", physical: "抗菌消炎、促進皮膚再生", emotional: "穩定情緒、消除焦慮", meridians: "脾經、胃經、大腸經" },
  { name: "檸檬香茅", components: "單萜醛 (檸檬醛)", physical: "強效驅蟲除臭、舒緩肌肉痠痛", emotional: "提振活力、消除疲勞", meridians: "脾經、胃經、肝經" },
  { name: "月桂", components: "氧化物 (1,8-桉油醇)", physical: "抗菌、促進淋巴循環", emotional: "強化、活化、增強信心", meridians: "肺經、脾經" },
  { name: "絲柏", components: "單萜烯 (α-蒎烯)", physical: "收斂止汗、舒緩浮腫", emotional: "平復情緒、收斂脾氣", meridians: "肝經、腎經、膀胱經" },
  { name: "大西洋雪松", components: "倍半萜酮 (大西洋酮)", physical: "促進淋巴流動、強健髮根", emotional: "鎮靜冥想、降低焦慮", meridians: "腎經、脾經、肺經、三焦經" },
  { name: "檀香", components: "倍半萜醇 (檀香醇)", physical: "護膚保濕、抗菌", emotional: "鎮靜效果、促進冥想和放鬆", meridians: "心經、脾經、腎經、心包經" },
  { name: "日本檜木", components: "單萜烯、倍半萜醇", physical: "抗菌、促進呼吸道健康", emotional: "舒緩壓力、平靜心靈", meridians: "肺經、肝經" },
  { name: "紅桔", components: "單萜烯 (檸檬烯)", physical: "促進消化、溫和抗菌", emotional: "安撫情緒、舒緩緊張", meridians: "肝經、脾經、胃經" },
  { name: "柑橘", components: "單萜烯 (檸檬烯)", physical: "促進食慾、幫助消化", emotional: "提振情緒、帶來快樂", meridians: "肝經、脾經、胃經" },
  { name: "黑胡椒", components: "倍半萜烯 (β-石竹烯)", physical: "溫暖身心、促進血液循環", emotional: "激勵心智、給予勇氣", meridians: "胃經、大腸經、腎經" },
  { name: "甜馬鬱蘭", components: "單萜醇 (萜品烯-4-醇)", physical: "舒緩肌肉痠痛、幫助消化", emotional: "放鬆緊繃神經、舒緩焦慮", meridians: "心經、肝經、脾經" },
  { name: "丁香", components: "酚類 (丁香酚)", physical: "強效抗菌、止痛", emotional: "提振精神、增強記憶", meridians: "腎經、脾經、胃經" },
  { name: "乳香", components: "單萜烯 (α-蒎烯)", physical: "促進細胞再生、抗老化", emotional: "寧靜、沉穩、深沉放鬆", meridians: "肺經、心經、腎經" },
  { name: "安息香", components: "酯類 (苯甲酸苄酯)", physical: "舒緩呼吸道、修復龜裂皮膚", emotional: "強效鎮靜、紓壓、抗沮喪", meridians: "脾經、肺經、心經" },
  { name: "銀艾", components: "單萜酮、氧化物、倍半萜烯", physical: "舒緩經痛、抗菌", emotional: "放鬆情緒、舒緩焦慮", meridians: "肝經、脾經、腎經" },
  { name: "檸檬", components: "單萜烯 (檸檬烯)", physical: "增強免疫力、淨化空氣", emotional: "澄清思緒、提升專注", meridians: "肝經、膽經、胃經" },
  { name: "錫蘭肉桂", components: "芳香醛 (肉桂醛)", physical: "強效抗菌、促進循環", emotional: "溫暖心靈、消除疲勞", meridians: "腎經、心經、脾經" },
  { name: "肉豆蔻", components: "單萜烯、醚類", physical: "促進消化、舒緩肌肉疼痛", emotional: "激勵情緒、恢復活力", meridians: "脾經、胃經、大腸經" },
  { name: "玫瑰草", components: "單萜醇 (香葉醇)", physical: "保濕護膚、抗菌", emotional: "安撫情緒、舒緩壓力", meridians: "心經、脾經" },
  { name: "古巴香脂", components: "倍半萜烯 (β-石竹烯)", physical: "強效抗發炎、舒緩疼痛", emotional: "穩定情緒、減輕焦慮", meridians: "肺經、腎經、大腸經" },
  { name: "歐白脂根", components: "單萜烯 (α-蒎烯)", physical: "促進消化、排毒", emotional: "重建穩定、給予支持與力量", meridians: "肺經、脾經、胃經" },
  { name: "佛手柑", components: "酯類、單萜烯", physical: "抗菌、促進消化", emotional: "抗憂鬱、放鬆焦慮、提振心情", meridians: "肝經、脾經、胃經、心包經、三焦經" },
  { name: "花梨木", components: "單萜醇 (沉香醇)", physical: "護膚、舒緩疲勞", emotional: "放鬆與平衡、減緩壓力", meridians: "心經、脾經、腎經" },
  { name: "綠花白千層", components: "氧化物 (1,8-桉油醇)", physical: "抗菌、淨化呼吸道", emotional: "提振精神、集中注意力", meridians: "肺經、膀胱經" },
  { name: "海茴香", components: "單萜烯 (γ-萜品烯)", physical: "抗氧化、促進皮膚再生", emotional: "舒緩壓力、放鬆心情", meridians: "肝經、脾經" },
  { name: "德國洋甘菊", components: "倍半萜烯、氧化物", physical: "強效抗發炎、舒緩過敏", emotional: "鎮靜情緒、減輕壓力", meridians: "肝經、脾經、胃經、三焦經" },
  { name: "胡蘿蔔籽", components: "倍半萜醇 (胡蘿蔔醇)", physical: "清除肝臟毒素、促進細胞再生", emotional: "淨化心靈、消除疲勞", meridians: "肝經、膽經、脾經" },
  { name: "岩玫瑰", components: "單萜烯 (α-蒎烯)", physical: "止血、抗痙攣", emotional: "平衡、鼓舞情緒、撫慰心靈", meridians: "心經、腎經" },
  { name: "甜茴香", components: "醚類 (反式茴香腦)", physical: "促進消化、利尿排毒", emotional: "舒緩緊張、給予勇氣", meridians: "胃經、脾經、腎經" },
  { name: "杜松漿果", components: "單萜烯 (α-蒎烯)", physical: "排除堆積水份、淨化", emotional: "激勵心靈、消除負面情緒", meridians: "腎經、膀胱經、肝經" },
  { name: "波旁天竺葵", components: "單萜醇 (香茅醇、香葉醇)", physical: "平衡荷爾蒙、調理皮脂", emotional: "振奮情緒、鎮定與減輕壓力", meridians: "肝經、脾經、腎經" },
  { name: "葡萄柚", components: "單萜烯 (檸檬烯)", physical: "促進淋巴循環、提振精神", emotional: "鼓舞情緒、使人走出不安感", meridians: "肝經、膽經、胃經" },
  { name: "羅文莎葉", components: "氧化物 (1,8-桉油醇)", physical: "強效抗病毒、提升免疫", emotional: "舒緩焦慮、提振精神", meridians: "肺經、肝經" },
  { name: "胡椒薄荷", components: "單萜醇、單萜酮", physical: "促進消化、緩解頭痛", emotional: "提神醒腦、澄清思緒", meridians: "肝經、膽經、胃經" },
  { name: "綠薄荷", components: "單萜酮 (香芹酮)", physical: "舒緩消化不良、溫和抗菌", emotional: "提振精神、減輕疲勞", meridians: "肝經、胃經" },
  { name: "苦橙葉", components: "酯類、單萜醇", physical: "放鬆肌肉、抗痙攣", emotional: "平衡提神、撫平易怒和緊張", meridians: "心經、肝經、心包經" },
  { name: "歐洲赤松", components: "單萜烯 (α-蒎烯)", physical: "舒緩呼吸道、促進循環", emotional: "心靈平靜、清新提神", meridians: "肺經、腎經" },
  { name: "綠香桃木", components: "氧化物、單萜烯", physical: "抗菌、抗痙攣", emotional: "放鬆情緒、平衡身心", meridians: "肺經、肝經" },
  { name: "桉油醇迷迭香", components: "氧化物 (1,8-桉油醇)", physical: "舒緩肌肉痠痛、促進循環", emotional: "提升精神與專注力", meridians: "肺經、肝經" },
  { name: "馬鞭草酮迷迭香", components: "單萜酮 (馬鞭草酮)", physical: "促進肝臟排毒、護膚", emotional: "澄清思緒、增強記憶", meridians: "肝經、膽經" },
  { name: "鼠尾草", components: "單萜酮 (側柏酮)", physical: "抗菌、舒緩喉嚨痛", emotional: "舒緩壓力、放鬆心情", meridians: "肺經、肝經、腎經" },
  { name: "快樂鼠尾草", components: "酯類 (乙酸沉香酯)", physical: "舒緩經期不適、放鬆肌肉", emotional: "放鬆緊繃神經、引發幸福感", meridians: "肝經、腎經、心經、三焦經" },
  { name: "檸檬馬鞭草", components: "單萜醛 (檸檬醛)", physical: "促進消化、抗發炎", emotional: "舒緩焦慮、鎮靜情緒", meridians: "肝經、脾經、胃經" },
  { name: "黑雲杉", components: "單萜烯、酯類", physical: "提高環境適應力與耐受度", emotional: "讓人有勇氣面對生命的挑戰", meridians: "腎經、肺經" },
  { name: "沒藥", components: "倍半萜烯", physical: "抗菌、修復傷口、平衡荷爾蒙", emotional: "安神、重新振作起來", meridians: "脾經、胃經、腎經" },
  { name: "芳枸葉", components: "單萜烯、氧化物、單萜醇", physical: "抗菌、舒緩呼吸道", emotional: "釋放深層情緒、平衡身心", meridians: "肺經、心經" },
  { name: "芳樟", components: "單萜醇 (沉香醇)", physical: "抗菌、舒緩肌肉疼痛", emotional: "安撫情緒、減輕壓力", meridians: "心經、脾經" },
  { name: "白玉蘭葉", components: "單萜醇 (沉香醇)", physical: "補氣、抗菌、排除廢水", emotional: "幫助安定與堅強、鎮定情緒", meridians: "心經、肺經、脾經" },
  { name: "阿米香樹", components: "倍半萜醇 (纈草醇、欖香醇)", physical: "靜脈循環、抗痙攣、皮膚保濕", emotional: "鎮靜安神、助眠、舒緩壓力", meridians: "肝經、心經" },
  { name: "小茴香", components: "醛類、單萜烯 (小茴香醛、檸檬烯)", physical: "幫助消化、緩解胃腸脹氣", emotional: "清掃不愉快記憶、處理沮喪", meridians: "脾經、胃經" },
  { name: "穗甘松", components: "倍半萜酮 (纈草酮)", physical: "抗菌、抗炎、舒緩心血管", emotional: "鎮靜、緩解焦慮、促進睡眠", meridians: "心經、脾經" },
  { name: "桔葉", components: "酯類 (鄰氨基苯甲酸二甲酯)", physical: "抗痙攣、消炎、助消化", emotional: "神經鎮靜、舒緩焦慮、助眠", meridians: "肝經、脾經" },
  { name: "樺木", components: "酯類 (水楊酸甲酯)", physical: "止痛、消除尿酸、利尿消水腫", emotional: "賦予活力、振奮、醒神通竅", meridians: "腎經、膀胱經" },
  { name: "犬香薷", components: "單萜醇 (沉香醇)", physical: "收斂舒敏、鎮定肌膚、抗菌", emotional: "撫平情緒、鎮靜、給予安撫", meridians: "心經、肺經" },
  { name: "東印度檸檬香茅", components: "單萜醛 (檸檬醛)", physical: "消除乳酸、促進循環、殺菌", emotional: "激勵、復甦、提振、消除疲勞", meridians: "脾經、胃經" }
];
export const botanicalIdentities = [
  "Cananga odorata", "Lavandula angustifolia", "Melaleuca alternifolia", "Eucalyptus radiata",
  "Lavandula latifolia", "Thymus vulgaris", "Thymus serpyllum", "Zingiber officinale",
  "Chrysopogon zizanioides", "Pogostemon cablin", "Cymbopogon citratus", "Laurus nobilis",
  "Cupressus sempervirens", "Cedrus atlantica", "Santalum album", "Chamaecyparis obtusa",
  "Citrus reticulata", "Citrus reticulata", "Piper nigrum", "Origanum majorana",
  "Syzygium aromaticum", "Boswellia sacra", "Styrax benzoin", "Artemisia ludoviciana",
  "Citrus limon", "Cinnamomum verum", "Myristica fragrans", "Cymbopogon martinii",
  "Copaifera officinalis", "Angelica archangelica", "Citrus bergamia", "Aniba rosaeodora",
  "Melaleuca quinquenervia", "Crithmum maritimum", "Matricaria recutita", "Daucus carota",
  "Cistus ladanifer", "Foeniculum vulgare", "Juniperus communis", "Pelargonium graveolens",
  "Citrus × paradisi", "Cinnamomum camphora", "Mentha × piperita", "Mentha spicata",
  "Citrus × aurantium", "Pinus sylvestris", "Myrtus communis", "Salvia rosmarinus",
  "Salvia rosmarinus", "Salvia officinalis", "Salvia sclarea", "Aloysia citrodora",
  "Picea mariana", "Commiphora myrrha", "Taxandria fragrans", "Cinnamomum camphora ct. linalool",
  "Magnolia × alba", "Amyris balsamifera", "Cuminum cyminum", "Nardostachys jatamansi",
  "Citrus reticulata", "Betula lenta", "Mosla scabra", "Cymbopogon flexuosus"
];
